import type { Figure } from "./schema";

// Hotspot boxes are percentages of the drawing (x, w of width; y, h of height).
// The drawings live in components/FigureArt.tsx; keep the two in step.
export const figures: Figure[] = [
  {
    id: "mitochondrion-cutaway",
    title: "Mitochondrion, cutaway",
    alt: "Diagram of a mitochondrion showing outer membrane, inner membrane folded into cristae, matrix, circular DNA, ribosomes and oxysomes",
    kind: "mitochondrion",
    shows: "Double membrane, cristae surface, matrix contents.",
    not: "A chloroplast. No grana. Not a bacterium by itself, though it has bacterial-style DNA.",
    citation: "Original teaching diagram. Study pointer: NCERT Class 11 Biology Ch 8, mitochondria.",
    hotspots: [
      { id: "outer", label: "Outer membrane", x: 40, y: 11, w: 20, h: 8, note: "Smooth and porous; porins let small solutes in. This is not the site of the ETC.", conceptId: "mitochondria" },
      { id: "inner", label: "Inner membrane (cristae)", x: 23, y: 21, w: 8, h: 30, note: "Folded into cristae. Electron transport chain and ATP synthase sit here.", termId: "cristae" },
      { id: "ims", label: "Intermembrane space", x: 64, y: 79, w: 14, h: 6, note: "Narrow gap between the two membranes. Protons pile up here during the ETC.", conceptId: "mitochondria" },
      { id: "matrix", label: "Matrix", x: 52, y: 55, w: 7, h: 17, note: "Krebs cycle enzymes, circular DNA, 70S ribosomes.", termId: "matrix" },
      { id: "dna", label: "mtDNA", x: 14, y: 43, w: 8, h: 14, note: "Circular DNA, like many bacteria. One reason we call the organelle semi-autonomous.", termId: "semi-autonomous" },
      { id: "oxysome", label: "Oxysomes", x: 34, y: 52, w: 10, h: 27, note: "F0–F1 particles on the matrix face of the cristae. They make ATP.", termId: "oxysome" },
    ],
  },
  {
    id: "mitosis-stages",
    title: "Mitosis in an animal cell",
    alt: "Five panels: prophase, metaphase, anaphase, telophase, cytokinesis",
    kind: "mitosis",
    shows: "Order of karyokinesis, then a cleavage furrow. Red and blue mark the two homologues of each pair.",
    not: "Meiosis. Homologues do not pair. No crossing over.",
    citation: "Original teaching diagram. Study pointer: NCERT Class 11 Biology Ch 10, M phase.",
    hotspots: [
      { id: "prophase", label: "1 Prophase", x: 1, y: 8, w: 18, h: 80, note: "Chromosomes condense. Nuclear envelope starts to break (dashed). Centrosomes move apart and the spindle begins.", conceptId: "mitosis" },
      { id: "metaphase", label: "2 Metaphase", x: 20, y: 8, w: 18, h: 80, note: "Chromosomes on the equator. Kinetochores of sisters face opposite poles.", termId: "kinetochore" },
      { id: "anaphase", label: "3 Anaphase", x: 39, y: 8, w: 18, h: 80, note: "Centromeres split. Sister chromatids move to opposite poles, arms trailing.", termId: "chromatid" },
      { id: "telophase", label: "4 Telophase", x: 58, y: 8, w: 18, h: 80, note: "Nuclear envelopes and nucleoli return. Chromosomes decondense. Reverse of prophase.", conceptId: "mitosis" },
      { id: "cyto", label: "5 Cytokinesis", x: 77, y: 8, w: 22, h: 80, note: "Animal: furrow from the edge. Plant: cell plate from the centre.", termId: "cytokinesis" },
    ],
  },
  {
    id: "plant-cell-map",
    title: "Plant cell map",
    alt: "Labelled plant cell with wall, plasma membrane, large vacuole, chloroplasts, nucleus, Golgi, ER and mitochondria",
    kind: "plant-cell",
    shows: "Cell wall, large vacuole, chloroplasts, nucleus pushed to the side, mitochondria.",
    not: "An animal cell. No centrioles shown. Not a prokaryote.",
    citation: "Original SVG map. Study pointer: NCERT Class 11 Biology Ch 8 overview.",
    hotspots: [
      { id: "wall", label: "Cell wall", x: 3, y: 0, w: 20, h: 4.5, note: "Cellulose, outside the membrane. Non-living. Gaps on the right edge are plasmodesmata.", conceptId: "cell-wall" },
      { id: "pm", label: "Plasma membrane", x: 28, y: 5, w: 16, h: 4.5, note: "Living membrane pressed against the wall by turgor.", conceptId: "plasma-membrane" },
      { id: "vac", label: "Vacuole", x: 34, y: 26, w: 36, h: 48, note: "Tonoplast bag. Turgor and storage; crystals may sit here.", conceptId: "vacuole" },
      { id: "chl", label: "Chloroplast", x: 8, y: 60, w: 16, h: 14, note: "Green plastid. Double membrane, grana inside.", conceptId: "plastids" },
      { id: "nuc", label: "Nucleus", x: 76, y: 14, w: 16, h: 25, note: "Envelope with pores, chromatin, nucleolus. Pushed aside by the vacuole.", conceptId: "nucleus" },
      { id: "golgi", label: "Dictyosome", x: 53, y: 10, w: 15, h: 10, note: "A Golgi stack. Plant cells have many.", termId: "dictyosome" },
      { id: "er", label: "ER", x: 77, y: 44, w: 16, h: 13, note: "Membrane tanks; the rough part carries ribosomes.", conceptId: "endoplasmic-reticulum" },
      { id: "mit", label: "Mitochondrion", x: 80, y: 79, w: 12, h: 9, note: "Power plant. Also in plant cells.", conceptId: "mitochondria" },
    ],
  },
  {
    id: "animal-cell-map",
    title: "Animal cell map",
    alt: "Labelled animal cell with plasma membrane, nucleus, centrioles, Golgi, lysosomes, rough ER and mitochondria",
    kind: "animal-cell",
    shows: "No cell wall, centriole pair, lysosomes, mitochondria.",
    not: "A plant cell. No chloroplasts. No large central vacuole.",
    citation: "Original SVG map. Study pointer: NCERT Class 11 Biology Ch 8 overview.",
    hotspots: [
      { id: "mem", label: "Plasma membrane", x: 40, y: 2, w: 20, h: 7, note: "Outer boundary in animals. No wall outside it.", conceptId: "plasma-membrane" },
      { id: "cen", label: "Centrioles", x: 21, y: 24, w: 9, h: 13, note: "Two 9 + 0 cartwheels at right angles in the centrosome.", conceptId: "centriole" },
      { id: "gol", label: "Golgi", x: 62, y: 17, w: 15, h: 17, note: "Stacked cisternae with budding vesicles. Packing and shipping.", conceptId: "golgi-apparatus" },
      { id: "lys", label: "Lysosomes", x: 77, y: 49, w: 9, h: 15, note: "Single-membrane bags of acid hydrolases.", conceptId: "lysosome" },
      { id: "rer", label: "Rough ER", x: 59, y: 51, w: 13, h: 19, note: "Ribosome-studded tanks next to the nucleus.", conceptId: "endoplasmic-reticulum" },
      { id: "nuc2", label: "Nucleus", x: 38, y: 35, w: 20, h: 32, note: "Usually one, central. Dark knot = nucleolus; dashed threads = chromatin.", conceptId: "nucleus" },
      { id: "mito2", label: "Mitochondrion", x: 24, y: 65, w: 13, h: 12, note: "Double membrane with cristae.", conceptId: "mitochondria" },
    ],
  },
  {
    id: "bacterium-map",
    title: "Prokaryotic cell map",
    alt: "Bacterium with capsule, wall, plasma membrane, mesosome, nucleoid, plasmids, ribosomes, pili and flagellum",
    kind: "bacterium",
    shows: "Envelope, nucleoid, plasmids, 70S ribosomes, flagellum. No membrane organelles.",
    not: "A mitochondrion. No nucleus. No ER.",
    citation: "Original SVG map. Study pointer: NCERT Class 11 Biology Ch 8, prokaryotic cells.",
    hotspots: [
      { id: "env", label: "Cell envelope", x: 40, y: 18, w: 20, h: 9, note: "Glycocalyx (dashed) + wall of peptidoglycan + plasma membrane (double line).", termId: "peptidoglycan" },
      { id: "nucoid", label: "Nucleoid", x: 31, y: 39, w: 20, h: 22, note: "Naked DNA region. No envelope, no nucleolus.", termId: "nucleoid" },
      { id: "plas", label: "Plasmids", x: 61, y: 34, w: 10, h: 14, note: "Extra circular DNA.", termId: "plasmid" },
      { id: "meso", label: "Mesosome", x: 19, y: 58, w: 10, h: 16, note: "Infolded membrane (textbook).", termId: "mesosome" },
      { id: "rib", label: "70S ribosomes", x: 52, y: 56, w: 12, h: 12, note: "Protein factories in the cytoplasm; a chain of them is a polysome.", termId: "70s" },
      { id: "flag", label: "Flagellum", x: 84, y: 42, w: 15, h: 16, note: "Bacterial flagellum is flagellin, not 9 + 2.", conceptId: "prokaryotic-cell" },
    ],
  },
  {
    id: "meiosis-overview",
    title: "Meiosis I versus meiosis II",
    alt: "Two rows: meiosis I separates homologues; meiosis II separates sister chromatids into four haploid cells",
    kind: "meiosis",
    shows: "Homologue separation in I, chromatid separation in II. Red = one homologue, blue = its partner.",
    not: "Mitosis. Chromosome number is halved only in meiosis I.",
    citation: "Original teaching diagram. Study pointer: NCERT Class 11 Biology Ch 10, meiosis.",
    hotspots: [
      { id: "mi", label: "Meiosis I", x: 1, y: 2, w: 98, h: 46, note: "Reductional. Homologues separate. Each daughter is n, but chromosomes still have two chromatids.", conceptId: "meiosis" },
      { id: "chiasma", label: "Chiasma", x: 7, y: 16, w: 12, h: 26, note: "Prophase I: a bivalent whose non-sister chromatids have crossed over.", termId: "chiasma" },
      { id: "mii", label: "Meiosis II", x: 1, y: 52, w: 98, h: 46, note: "Equational. Looks like mitosis, but in haploid cells. Ends in four n cells.", conceptId: "meiosis" },
    ],
  },
  {
    id: "membrane-mosaic",
    title: "Fluid mosaic membrane",
    alt: "Phospholipid bilayer with an integral protein, a peripheral protein, cholesterol and sugar chains on the outer face",
    kind: "membrane",
    shows: "Bilayer, integral and peripheral proteins, cholesterol, sugars on the outer face.",
    not: "A cell wall. Not a rigid sandwich of protein–lipid–protein as the old model said.",
    citation: "Original diagram after Singer and Nicolson 1972. Study pointer: NCERT Class 11 Biology Ch 8, cell membrane.",
    hotspots: [
      { id: "head", label: "Polar heads", x: 5, y: 27, w: 18, h: 10, note: "Hydrophilic. Face water on both sides.", termId: "amphipathic" },
      { id: "tail", label: "Fatty tails", x: 34, y: 40, w: 8, h: 20, note: "Hydrophobic core. Barrier to ions.", termId: "amphipathic" },
      { id: "chol", label: "Cholesterol", x: 45, y: 36, w: 5, h: 11, note: "Animal membranes: tunes fluidity.", conceptId: "plasma-membrane" },
      { id: "prot", label: "Integral protein", x: 59, y: 22, w: 18, h: 57, note: "Spans the bilayer. May be a channel or pump.", termId: "fluid-mosaic" },
      { id: "peri", label: "Peripheral protein", x: 27, y: 70, w: 12, h: 12, note: "Sits on the surface; easy to wash off.", termId: "fluid-mosaic" },
      { id: "glyco", label: "Sugar chains", x: 62, y: 10, w: 12, h: 13, note: "Glycoproteins and glycolipids on the outer face: cell identity.", conceptId: "plasma-membrane" },
    ],
  },
];

export const figureById = Object.fromEntries(figures.map((f) => [f.id, f])) as Record<
  string,
  Figure
>;
