import type { Term } from "./schema";

export const terms: Term[] = [
  {
    id: "cristae",
    word: "cristae",
    pronunciation: "KRIS-tee",
    hover: "Folds of the inner mitochondrial membrane.",
    etymology: "Latin crista, a crest or comb.",
    layers: {
      l0: "Shelf-like folds inside a mitochondrion.",
      l1: "The inner membrane is crumpled so more machines can sit on it.",
      l2: "Cristae raise the surface area for electron transport and ATP synthase.",
      l3: "Do not call thylakoid stacks cristae. Cristae are mitochondrial; grana are chloroplast.",
    },
    dontConfuse: "grana / thylakoids in chloroplasts",
    examLine: "Site of oxysomes / F0–F1 particles on the inner membrane.",
    related: ["matrix", "oxysome", "mitochondria"],
    conceptId: "mitochondria",
  },
  {
    id: "matrix",
    word: "matrix",
    pronunciation: "MAY-triks",
    hover: "The inner fluid of a mitochondrion.",
    etymology: "Latin matrix, womb or mould.",
    layers: {
      l0: "The soup inside the inner membrane.",
      l1: "Krebs cycle enzymes live here, with mitochondrial DNA and 70S ribosomes.",
      l2: "Circular mtDNA and protein synthesis make mitochondria semi-autonomous.",
    },
    dontConfuse: "stroma of chloroplast",
    examLine: "Krebs cycle occurs in the mitochondrial matrix.",
    related: ["cristae", "70s", "semi-autonomous"],
    conceptId: "mitochondria",
  },
  {
    id: "stroma",
    word: "stroma",
    pronunciation: "STROH-muh",
    hover: "The fluid of a chloroplast, around the thylakoids.",
    etymology: "Greek stroma, a mattress or bed.",
    layers: {
      l0: "The chloroplast’s inner juice.",
      l1: "Dark-reaction enzymes sit in the stroma. DNA and 70S ribosomes sit here too.",
    },
    dontConfuse: "matrix of mitochondrion; stoma of leaf",
    examLine: "Calvin cycle is stromal; light reaction is thylakoid.",
    related: ["grana", "thylakoid"],
    conceptId: "plastids",
  },
  {
    id: "grana",
    word: "grana",
    pronunciation: "GRAH-nuh",
    hover: "Stacks of thylakoid discs in a chloroplast.",
    etymology: "Latin granum, a grain (plural grana).",
    layers: {
      l0: "Pancake stacks that catch light.",
    },
    dontConfuse: "cristae",
    examLine: "Grana = stacked thylakoids; stroma lamellae join them.",
    related: ["thylakoid", "stroma"],
    conceptId: "plastids",
  },
  {
    id: "thylakoid",
    word: "thylakoid",
    pronunciation: "THY-luh-koyd",
    hover: "A flattened membrane sac that holds chlorophyll.",
    etymology: "Greek thylakos, a sack.",
    layers: { l0: "The green membrane pocket of a chloroplast." },
    dontConfuse: "crista",
    examLine: "Photolysis and light harvest occur on thylakoid membranes.",
    related: ["grana", "stroma"],
    conceptId: "plastids",
  },
  {
    id: "mesosome",
    word: "mesosome",
    pronunciation: "MEE-so-sohm",
    hover: "Infolded plasma membrane seen in some bacterial cells.",
    etymology: "Greek mesos, middle + soma, body.",
    layers: {
      l0: "A wrinkle of the bacterial cell membrane.",
      l1: "Older books link it to respiration and DNA attachment. Many are now seen as prep artefacts.",
      l3: "NEET still lists mesosomes. Write the textbook function, then know the artefact debate at L4.",
    },
    dontConfuse: "cristae of mitochondria (bacteria have no mitochondria)",
    examLine: "Help in respiration, secretion, and nucleoid anchoring in prokaryotes (as per NCERT wording).",
    related: ["nucleoid"],
    conceptId: "prokaryotic-cell",
  },
  {
    id: "dictyosome",
    word: "dictyosome",
    pronunciation: "DIK-tee-oh-sohm",
    hover: "A Golgi stack, especially in plant cells.",
    etymology: "Greek diktyon, net + soma, body.",
    layers: {
      l0: "One pile of Golgi cisternae.",
      l2: "Plant cells have many dictyosomes; animal cells often have one Golgi complex.",
    },
    dontConfuse: "ER cisternae",
    examLine: "Golgi in plants = dictyosomes; packing of materials.",
    related: ["cisternae"],
    conceptId: "golgi-apparatus",
  },
  {
    id: "cisternae",
    word: "cisternae",
    pronunciation: "sis-TUR-nee",
    hover: "Flattened membrane sacs in ER or Golgi.",
    etymology: "Latin cisterna, a reservoir.",
    layers: { l0: "Flat membrane tanks stacked like trays." },
    dontConfuse: "cristae",
    examLine: "RER cisternae bear ribosomes; Golgi cisternae do not.",
    related: ["dictyosome"],
    conceptId: "endoplasmic-reticulum",
  },
  {
    id: "protoplasm",
    word: "protoplasm",
    pronunciation: "PROH-toh-plaz-um",
    hover: "Living contents of the cell: cytoplasm plus nucleus.",
    etymology: "Greek protos, first + plasma, formed thing.",
    layers: {
      l0: "Everything living inside the cell wall or membrane.",
      l2: "Cytoplasm + nucleoplasm = protoplasm. Cell wall is not protoplasm.",
    },
    dontConfuse: "cytoplasm (excludes nucleus)",
    examLine: "CPMT: protoplasm vs non-protoplasmic inclusions.",
    related: ["cytoplasm", "ergastic"],
    conceptId: "protoplasm",
  },
  {
    id: "cytoplasm",
    word: "cytoplasm",
    pronunciation: "SY-toh-plaz-um",
    hover: "Cell contents outside the nucleus, including cytosol and organelles.",
    etymology: "Greek kytos, hollow + plasma.",
    layers: { l0: "The cell’s kitchen, not counting the nucleus." },
    dontConfuse: "protoplasm; cytosol (only the soluble part)",
    examLine: "Organelles except nucleus lie in cytoplasm.",
    related: ["protoplasm", "nucleoplasm"],
    conceptId: "protoplasm",
  },
  {
    id: "nucleoplasm",
    word: "nucleoplasm",
    pronunciation: "NEW-klee-oh-plaz-um",
    hover: "The fluid inside the nucleus.",
    etymology: "Latin nucleus + plasma.",
    layers: { l0: "Nuclear juice around chromatin." },
    dontConfuse: "cytoplasm",
    examLine: "Nucleoplasm + nuclear envelope + chromatin + nucleolus = nucleus.",
    related: ["chromatin", "nucleolus"],
    conceptId: "nucleus",
  },
  {
    id: "tonoplast",
    word: "tonoplast",
    pronunciation: "TOH-noh-plast",
    hover: "Membrane around the plant vacuole.",
    etymology: "Greek tonos, tension + plastos, formed.",
    layers: { l0: "The bag around the cell’s water tank." },
    dontConfuse: "plasma membrane",
    examLine: "Vacuole is bound by tonoplast; stores sap.",
    related: [],
    conceptId: "vacuole",
  },
  {
    id: "nucleoid",
    word: "nucleoid",
    pronunciation: "NEW-klee-oyd",
    hover: "Irregular DNA region in a prokaryote; no envelope.",
    etymology: "nucleus-like.",
    layers: { l0: "A DNA patch, not a true nucleus." },
    dontConfuse: "nucleus",
    examLine: "Prokaryotes: nucleoid, no histone-bound chromosomes like eukaryotes.",
    related: ["plasmid", "mesosome"],
    conceptId: "prokaryotic-cell",
  },
  {
    id: "plasmid",
    word: "plasmid",
    pronunciation: "PLAZ-mid",
    hover: "Small extra circular DNA in many bacteria.",
    etymology: "plasma + -id.",
    layers: { l0: "A bonus DNA ring, often with antibiotic genes." },
    dontConfuse: "nucleoid chromosome",
    examLine: "Plasmids are extra-chromosomal, used in genetic engineering.",
    related: ["nucleoid"],
    conceptId: "prokaryotic-cell",
  },
  {
    id: "peptidoglycan",
    word: "peptidoglycan",
    pronunciation: "pep-ti-doh-GLY-kan",
    hover: "Sugar–peptide mesh of most bacterial cell walls.",
    etymology: "peptide + glycan.",
    layers: { l0: "The stiff bag around a bacterium." },
    dontConfuse: "cellulose of plants; chitin of fungi",
    examLine: "Bacterial wall = peptidoglycan (mucopeptide).",
    related: [],
    conceptId: "prokaryotic-cell",
  },
  {
    id: "fluid-mosaic",
    word: "fluid mosaic",
    pronunciation: "FLOO-id moh-ZAY-ik",
    hover: "Singer–Nicolson model: lipids flow, proteins float in them.",
    etymology: "mosaic of mixed tiles that can slide.",
    layers: {
      l0: "A moving sea of fat with protein boats.",
      l2: "Quasi-fluid bilayer; proteins may be integral or peripheral.",
    },
    dontConfuse: "sandwich model of Davson–Danielli",
    examLine: "Most accepted model of plasma membrane.",
    related: ["amphipathic"],
    conceptId: "plasma-membrane",
  },
  {
    id: "amphipathic",
    word: "amphipathic",
    pronunciation: "am-fi-PATH-ik",
    hover: "A molecule with both water-loving and water-hating ends.",
    etymology: "Greek amphi, both + pathos, feeling.",
    layers: { l0: "Phospholipids have a wet head and two oily tails." },
    dontConfuse: "amphibian (animals)",
    examLine: "Phospholipids are amphipathic; they form bilayers spontaneously.",
    related: ["fluid-mosaic"],
    conceptId: "plasma-membrane",
  },
  {
    id: "plasmodesmata",
    word: "plasmodesmata",
    pronunciation: "plaz-moh-DEZ-muh-tuh",
    hover: "Cytoplasmic tunnels through plant cell walls.",
    etymology: "plasma + Greek desmos, bond.",
    layers: { l0: "Tiny doors between plant cells." },
    dontConfuse: "gap junctions of animals",
    examLine: "Symplast continuity via plasmodesmata.",
    related: ["middle-lamella"],
    conceptId: "cell-wall",
  },
  {
    id: "middle-lamella",
    word: "middle lamella",
    pronunciation: "MID-ul luh-MELL-uh",
    hover: "Pectin glue between two plant cell walls.",
    etymology: "lamella, a thin plate.",
    layers: { l0: "The jam between two onion cells." },
    dontConfuse: "primary wall",
    examLine: "Calcium pectate; cementing layer.",
    related: ["plasmodesmata"],
    conceptId: "cell-wall",
  },
  {
    id: "oxysome",
    word: "oxysome",
    pronunciation: "OK-si-sohm",
    hover: "ATP-synthase particle on the inner mitochondrial membrane.",
    etymology: "oxy- (oxygen/oxidation) + soma.",
    layers: { l0: "The lollipop that makes ATP." },
    dontConfuse: "ribosome",
    examLine: "F0–F1 / elementary particles / oxysomes on cristae.",
    related: ["cristae"],
    conceptId: "mitochondria",
  },
  {
    id: "70s",
    word: "70S ribosome",
    pronunciation: "SEV-en-tee ess",
    hover: "Prokaryote-type ribosome (also in mitochondria and chloroplasts).",
    etymology: "Svedberg sedimentation units, not additive as 50+30=70.",
    layers: { l0: "Smaller protein factory, bacterial style." },
    dontConfuse: "80S cytosolic eukaryotic ribosomes",
    examLine: "70S = 50S + 30S; evidence for endosymbiosis.",
    related: ["80s", "semi-autonomous"],
    conceptId: "mitochondria",
  },
  {
    id: "80s",
    word: "80S ribosome",
    pronunciation: "AY-tee ess",
    hover: "Cytosolic ribosome of eukaryotes.",
    etymology: "Svedberg units; 60S + 40S ≈ 80S.",
    layers: { l0: "The bigger factory in the eukaryotic cytosol." },
    dontConfuse: "70S",
    examLine: "RER has 80S ribosomes in eukaryotes.",
    related: ["70s"],
    conceptId: "endoplasmic-reticulum",
  },
  {
    id: "semi-autonomous",
    word: "semi-autonomous",
    pronunciation: "sem-ee aw-TAW-nuh-mus",
    hover: "Organelles with own DNA that still need nuclear genes.",
    etymology: "half self-governing.",
    layers: { l0: "They bake some of their own cake, not all." },
    dontConfuse: "fully independent bacteria",
    examLine: "Mitochondria and chloroplasts are semi-autonomous.",
    related: ["endosymbiont", "70s"],
    conceptId: "mitochondria",
  },
  {
    id: "endosymbiont",
    word: "endosymbiont theory",
    pronunciation: "en-doh-SIM-bee-ont",
    hover: "Mitochondria and chloroplasts came from engulfed bacteria.",
    etymology: "endo, inside + symbiosis, living together.",
    layers: { l0: "An old bacterium that moved in and never left." },
    dontConfuse: "parasitism",
    examLine: "Double membrane, circular DNA, 70S ribosomes support it.",
    related: ["semi-autonomous"],
    conceptId: "mitochondria",
  },
  {
    id: "chromatin",
    word: "chromatin",
    pronunciation: "KROH-muh-tin",
    hover: "DNA plus proteins, loosely spread in a working nucleus.",
    etymology: "Greek chroma, colour (it stains).",
    layers: { l0: "Thread-like DNA furniture of the nucleus." },
    dontConfuse: "chromosome (packed for division)",
    examLine: "Euchromatin active; heterochromatin condensed.",
    related: ["nucleosome", "histone"],
    conceptId: "nucleus",
  },
  {
    id: "nucleosome",
    word: "nucleosome",
    pronunciation: "NEW-klee-oh-sohm",
    hover: "DNA wound around a histone octamer; beads on a string.",
    etymology: "nucleus + soma.",
    layers: { l0: "The first spool of packing DNA." },
    dontConfuse: "nucleolus",
    examLine: "Nucleosome is the repeating unit of chromatin.",
    related: ["histone", "chromatin"],
    conceptId: "nucleus",
  },
  {
    id: "histone",
    word: "histone",
    pronunciation: "HISS-tone",
    hover: "Basic proteins that pack eukaryotic DNA.",
    etymology: "histos, tissue + -one.",
    layers: { l0: "The spools DNA wraps around." },
    dontConfuse: "non-histone proteins",
    examLine: "H2A, H2B, H3, H4 octamer; H1 linker. Bacteria lack typical histones.",
    related: ["nucleosome"],
    conceptId: "nucleus",
  },
  {
    id: "nucleolus",
    word: "nucleolus",
    pronunciation: "new-KLEE-oh-lus",
    hover: "Nuclear factory for rRNA and ribosomal subunits.",
    etymology: "little nucleus.",
    layers: { l0: "The dark knot that makes ribosome parts." },
    dontConfuse: "nucleus; nucleosome",
    examLine: "Larger in cells that make lots of protein.",
    related: ["chromatin"],
    conceptId: "nucleus",
  },
  {
    id: "kinetochore",
    word: "kinetochore",
    pronunciation: "ki-NET-oh-kor",
    hover: "Protein plate on the centromere where spindle fibres attach.",
    etymology: "Greek kinetos, moving + choros, place.",
    layers: { l0: "The handle the spindle grabs." },
    dontConfuse: "centromere (DNA region) vs kinetochore (protein)",
    examLine: "Spindle microtubules bind kinetochore at metaphase.",
    related: ["centromere", "chromatid"],
    conceptId: "mitosis",
  },
  {
    id: "centromere",
    word: "centromere",
    pronunciation: "SEN-troh-meer",
    hover: "Constricted DNA region that holds sister chromatids.",
    etymology: "centre + meros, part.",
    layers: { l0: "The belt of a chromosome." },
    dontConfuse: "centrosome; centriole",
    examLine: "Metacentric, submetacentric, acrocentric, telocentric by centromere position.",
    related: ["kinetochore", "chromatid"],
    conceptId: "mitosis",
  },
  {
    id: "chromatid",
    word: "chromatid",
    pronunciation: "KROH-muh-tid",
    hover: "One of two identical DNA copies joined at the centromere.",
    etymology: "chroma + -id.",
    layers: { l0: "One twin of a duplicated chromosome." },
    dontConfuse: "chromosome (may be one or two chromatids)",
    examLine: "After S phase each chromosome has two sister chromatids.",
    related: ["centromere"],
    conceptId: "cell-cycle",
  },
  {
    id: "synapsis",
    word: "synapsis",
    pronunciation: "si-NAP-sis",
    hover: "Pairing of homologous chromosomes in zygotene.",
    etymology: "Greek synapsis, a joining.",
    layers: { l0: "Homologues zip together." },
    dontConfuse: "synapse of neurons",
    examLine: "Synapsis in zygotene of prophase I.",
    related: ["bivalent", "crossing-over"],
    conceptId: "meiosis",
  },
  {
    id: "crossing-over",
    word: "crossing over",
    pronunciation: "KROSS-ing OH-ver",
    hover: "Exchange of segments between non-sister chromatids.",
    etymology: "descriptive English.",
    layers: { l0: "Homologues swap bits of DNA." },
    dontConfuse: "independent assortment",
    examLine: "Pachytene; chiasma visible in diplotene.",
    related: ["chiasma", "synapsis"],
    conceptId: "meiosis",
  },
  {
    id: "chiasma",
    word: "chiasma",
    pronunciation: "ky-AZ-muh",
    hover: "X-shaped cross where crossing over happened.",
    etymology: "Greek chiasma, cross-piece (chi, Χ).",
    layers: { l0: "The scar of a DNA swap, seen as an X." },
    dontConfuse: "centromere",
    examLine: "Chiasmata hold bivalents; terminalise by diakinesis.",
    related: ["crossing-over", "bivalent"],
    conceptId: "meiosis",
  },
  {
    id: "bivalent",
    word: "bivalent",
    pronunciation: "by-VAY-lent",
    hover: "A paired set of homologous chromosomes (four chromatids = tetrad).",
    etymology: "two powers / two units.",
    layers: { l0: "A couple of matching chromosomes stuck together." },
    dontConfuse: "a single duplicated chromosome in mitosis",
    examLine: "Number of bivalents = n (haploid number).",
    related: ["tetrad", "synapsis"],
    conceptId: "meiosis",
  },
  {
    id: "tetrad",
    word: "tetrad",
    pronunciation: "TET-rad",
    hover: "Four chromatids of a bivalent.",
    etymology: "Greek tetra, four.",
    layers: { l0: "Four DNA sisters in one paired set." },
    dontConfuse: "tetrad of spores after meiosis",
    examLine: "A bivalent is a tetrad of chromatids.",
    related: ["bivalent"],
    conceptId: "meiosis",
  },
  {
    id: "cytokinesis",
    word: "cytokinesis",
    pronunciation: "sy-toh-kye-NEE-sis",
    hover: "Division of cytoplasm after nuclear division.",
    etymology: "cyto + kinesis, movement.",
    layers: { l0: "The cell splits its kitchen after the nucleus splits." },
    dontConfuse: "karyokinesis",
    examLine: "Animals: furrow. Plants: cell plate.",
    related: ["cell-plate"],
    conceptId: "mitosis",
  },
  {
    id: "cell-plate",
    word: "cell plate",
    pronunciation: "sell playt",
    hover: "New wall that grows in the middle of a dividing plant cell.",
    etymology: "descriptive.",
    layers: { l0: "A wall that grows from the centre outward." },
    dontConfuse: "cleavage furrow",
    examLine: "Phragmoplast vesicles fuse to form cell plate.",
    related: ["cytokinesis"],
    conceptId: "mitosis",
  },
  {
    id: "amitosis",
    word: "amitosis",
    pronunciation: "ay-my-TOH-sis",
    hover: "Direct nuclear split without a spindle or distinct chromosomes.",
    etymology: "a- without + mitosis.",
    layers: { l0: "A simple pinch of the nucleus." },
    dontConfuse: "mitosis; meiosis",
    examLine: "Seen in some protozoa, foetal membranes; CPMT topic.",
    related: [],
    conceptId: "amitosis",
  },
  {
    id: "G0",
    word: "G0 phase",
    pronunciation: "jee nought",
    hover: "A quiet exit from the cycle; cell is not preparing to divide.",
    etymology: "Gap 0.",
    layers: { l0: "The cell sits this round out." },
    dontConfuse: "G1",
    examLine: "Neurons, some adult cells stay in G0; can be reversible in others.",
    related: [],
    conceptId: "cell-cycle",
  },
  {
    id: "ergastic",
    word: "ergastic inclusions",
    pronunciation: "er-GAS-tik",
    hover: "Non-living deposits in the cell: starch, crystals, oils.",
    etymology: "Greek ergastikos, of work / stored products.",
    layers: { l0: "The pantry, not the cook." },
    dontConfuse: "organelles",
    examLine: "CPMT: non-protoplasmic inclusions and their significance.",
    related: ["protoplasm"],
    conceptId: "protoplasm",
  },
  {
    id: "microsome",
    word: "microsome",
    pronunciation: "MY-kroh-sohm",
    hover: "Tiny vesicle from broken ER, seen after grinding cells in a lab.",
    etymology: "micro + soma.",
    layers: {
      l0: "A lab fragment of ER, not a true organelle in the living cell.",
      l3: "Old CPMT lists microsomes with organelles; they are artefacts of homogenisation.",
    },
    dontConfuse: "ribosome; mesosome",
    examLine: "Microsomes = fragmented ER + ribosomes in cell fractions.",
    related: [],
    conceptId: "endoplasmic-reticulum",
  },
  {
    id: "9-plus-2",
    word: "9+2 axoneme",
    pronunciation: "nine plus two",
    hover: "Nine outer microtubule doublets plus two central singlets in cilia/flagella.",
    etymology: "descriptive count.",
    layers: { l0: "The engine pattern of a waving cilium." },
    dontConfuse: "9+0 of centriole",
    examLine: "Eukaryotic cilia/flagella: 9+2; centriole: 9+0 triplets.",
    related: ["9-plus-0"],
    conceptId: "centriole",
  },
  {
    id: "9-plus-0",
    word: "9+0 cartwheel",
    pronunciation: "nine plus zero",
    hover: "Nine microtubule triplets, no central pair; centriole / basal body.",
    etymology: "descriptive count.",
    layers: { l0: "The cartwheel of the centriole." },
    dontConfuse: "9+2 axoneme",
    examLine: "Centriole: nine triplets of microtubules, hub and spokes.",
    related: ["9-plus-2"],
    conceptId: "centriole",
  },
  {
    id: "meristem",
    word: "meristem",
    pronunciation: "MER-ih-stem",
    hover: "Plant tissue that keeps dividing.",
    etymology: "Greek merizein, to divide.",
    layers: { l0: "The growing tips and cambium." },
    dontConfuse: "permanent tissue",
    examLine: "Apical, lateral, intercalary meristems.",
    related: ["parenchyma"],
    conceptId: "plant-tissues",
  },
  {
    id: "parenchyma",
    word: "parenchyma",
    pronunciation: "puh-REN-kih-muh",
    hover: "Living thin-walled packing tissue of plants.",
    etymology: "Greek para, beside + enchyma, infusion.",
    layers: { l0: "Soft living filler of the plant body." },
    dontConfuse: "collenchyma; sclerenchyma",
    examLine: "Isodiametric, living, intercellular spaces; photosynthesis, storage.",
    related: ["collenchyma", "sclerenchyma"],
    conceptId: "plant-tissues",
  },
  {
    id: "collenchyma",
    word: "collenchyma",
    pronunciation: "kuh-LEN-kih-muh",
    hover: "Living support tissue with unevenly thick cellulose walls.",
    etymology: "Greek kolla, glue.",
    layers: { l0: "Flexible living rods under the skin of a stem." },
    dontConfuse: "sclerenchyma (dead, lignin)",
    examLine: "Mechanical support in growing organs.",
    related: ["parenchyma"],
    conceptId: "plant-tissues",
  },
  {
    id: "sclerenchyma",
    word: "sclerenchyma",
    pronunciation: "skleh-REN-kih-muh",
    hover: "Dead thick-walled support; fibres and sclereids.",
    etymology: "Greek skleros, hard.",
    layers: { l0: "Stone-hard dead cells." },
    dontConfuse: "collenchyma",
    examLine: "Lignified; fibres and stone cells.",
    related: ["parenchyma"],
    conceptId: "plant-tissues",
  },
  {
    id: "apoenzyme",
    word: "apoenzyme",
    pronunciation: "ap-oh-EN-zyme",
    hover: "Protein part of an enzyme without its helper.",
    etymology: "apo, away from + enzyme.",
    layers: { l0: "The protein body of the enzyme, alone." },
    dontConfuse: "holoenzyme; coenzyme",
    examLine: "Apoenzyme + cofactor = holoenzyme.",
    related: ["holoenzyme", "coenzyme"],
    conceptId: "enzymes",
  },
  {
    id: "holoenzyme",
    word: "holoenzyme",
    pronunciation: "hol-oh-EN-zyme",
    hover: "Complete active enzyme: protein plus cofactor.",
    etymology: "holos, whole.",
    layers: { l0: "The working whole enzyme." },
    dontConfuse: "apoenzyme",
    examLine: "Holoenzyme = apoenzyme + prosthetic group/coenzyme.",
    related: ["apoenzyme"],
    conceptId: "enzymes",
  },
  {
    id: "coenzyme",
    word: "coenzyme",
    pronunciation: "koh-EN-zyme",
    hover: "Organic cofactor, often a vitamin derivative, loosely bound.",
    etymology: "co- + enzyme.",
    layers: { l0: "A vitamin-shaped helper that enzymes borrow." },
    dontConfuse: "metal cofactor; prosthetic group (tight)",
    examLine: "NAD, NADP, CoA are coenzymes.",
    related: ["apoenzyme"],
    conceptId: "enzymes",
  },
  {
    id: "Km",
    word: "Km",
    pronunciation: "kay em",
    hover: "Substrate concentration at half Vmax; affinity inverse.",
    etymology: "Michaelis constant.",
    layers: { l0: "How hungry the enzyme is for its substrate." },
    dontConfuse: "Vmax",
    examLine: "Low Km = high affinity.",
    related: [],
    conceptId: "enzymes",
  },
];

export const termById = Object.fromEntries(terms.map((t) => [t.id, t])) as Record<
  string,
  Term
>;
